<?php

/**
 * @file
 * Paragraph Bundle Card.
 *
 * Filename:     paragraph_bundle_card.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraph_bundle_card_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.paragraph_bundle_card') {
    return paragraphs_bundles__helper_render_readme();
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function paragraph_bundle_card_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__card_three_columns_bundle' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__card_two_columns_bundle' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__card_text_section_bundle' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__card_image_section_bundle' => [
      'base hook' => 'paragraph',
    ],

  ];
}
