<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_requirements().
 */
function views_rss_media_getid3_requirements($phase) {
  $requirements = [];

  if ($phase === 'install' && !class_exists(getID3::class)) {
    $requirements['views_rss_media_getid3'] = [
      'description' => t('Views RSS: Media getID3 requires the getID3 library.'),
      'severity' => REQUIREMENT_ERROR,
    ];
  }

  return $requirements;
}
