<?php

/**
 * @file
 * Paragraphs Bundles.
 *
 * Filename:     paragraphs_bundles.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraphs_bundles_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.paragraphs_bundles') {
    return paragraphs_bundles__helper_render_readme();
  }
  return NULL;
}

/**
 * Helper function to render README.md.
 */
function paragraphs_bundles__helper_render_readme() {
  $text = file_get_contents(__DIR__ . "/README.md");

  if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
    return '<pre>' . $text . '</pre>';
  }

  // Use the Markdown filter to render the README.
  $filter_manager = \Drupal::service('plugin.manager.filter');
  $settings = \Drupal::configFactory()
    ->get('markdown.settings')
    ->getRawData();
  $config = ['settings' => $settings];
  $filter = $filter_manager->createInstance('markdown', $config);
  return $filter->process($text, 'en');
}

/**
 * Implements hook_theme().
 */
function paragraphs_bundles_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__simple_bundle' => [
      'base hook' => 'paragraph',
    ],
    'field__entity_reference_revisions' => [
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function paragraphs_bundles_preprocess_page(&$variables) {
  $admin_theme = \Drupal::config('system.theme')->get('admin') ?: \Drupal::config('system.theme')->get('default');

  // No admin theme selected or value not existing. Cancel.
  if (empty($admin_theme) || !\Drupal::service('theme_handler')->themeExists($admin_theme)) {
    return;
  }

  $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);

  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute() && $admin_theme_name) {
    $variables['#attached']['library'][] = 'paragraphs_bundles/paragraphs-bundles-admin';
  }
}
