<?php

/**
 * @file
 * Paragraph Bundle Link.
 *
 * Filename:     paragraph_bundle_link.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraph_bundle_link_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.paragraph_bundle_link') {
    return paragraphs_bundles__helper_render_readme();
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function paragraph_bundle_link_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__link_section_bundle' => [
      'base hook' => 'paragraph',
    ],
  ];
}
