<?php

/**
 * @file
 * Paragraph Bundle Webform.
 *
 * Filename:     paragraph_bundle_webform.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraph_bundle_webform_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.paragraph_bundle_webform') {
    return paragraphs_bundles__helper_render_readme();
  }
  return NULL;
}

/**
 * Implements hook_theme() for the paragraph_bundle_webform submodule.
 */
function paragraph_bundle_webform_theme($existing, $type, $theme, $path) {
  $template_directory = \Drupal::service('extension.path.resolver')->getPath('module', 'paragraphs_bundles') . '/templates';

  return [
    'paragraph__webform_bundle' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--default',
      'path' => $template_directory,
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_paragraph_alter() for webform.
 */
function paragraph_bundle_webform_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  $bundle = $paragraph->bundle();

  // Add a template suggestion for paragraphs of type 'webform_bundle'.
  if ($bundle === 'webform_bundle') {
    $suggestions[] = 'paragraph__webform_bundle';
  }
}
